import '@/styles/globals.css'

import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Next.js Boilerplate',
  description: 'Generated by Jialin Yang',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="flex h-screen w-screen items-center justify-center">{children}</body>
    </html>
  )
}
